/** Plain-English explanations shown in tooltips. */
export const GLOSSARY = {
  BTO: 'Build-To-Order: a new HDB flat you book before it is built. You usually wait 3–4 years for keys.',
  OA: 'CPF Ordinary Account. Part of your monthly CPF goes here. You can use it for your flat (downpayment, stamp duty, legal fees, mortgage) but not for renovation or furniture.',
  CPF: 'Central Provident Fund. You and your employer pay a share of your salary into it every month.',
  cash: 'Money in your bank accounts. Some costs (option fee, renovation, furniture) can only be paid in cash.',
  application: 'The month you apply for the BTO launch.',
  booking: 'Flat selection appointment. You pick a unit and pay the option fee (cash).',
  AFL: 'Agreement for Lease: the contract you sign with HDB, usually within 9 months of booking. The first part of the downpayment and the stamp duty are due now.',
  keys: 'Key collection: the flat is ready. The rest of the downpayment is due and the loan starts. Mortgage payments begin the next month.',
  optionFee: 'A small cash fee to reserve the flat at booking ($500–$2,000). It counts towards your downpayment.',
  BSD: "Buyer's Stamp Duty: a tax on buying property, based on price (1% on the first $180k, 2% on the next $180k, 3% on the next $640k …). Due within 14 days of signing the AFL. CPF can be used.",
  downpayment: 'The part of the price you pay yourselves (not borrowed). With a 75% loan, it is 25% of the price, split between AFL and key collection.',
  staggered: 'Staggered Downpayment Scheme: pay a smaller part (2.5%) at AFL and the rest at key collection. For eligible first-timer couples (e.g. HFE letter obtained before the younger applicant turns 30).',
  DIA: 'Deferred Income Assessment: for young couples who are full-time students or NSFs (or finished within the last 12 months), with at least one of you aged 30 or below. You pay just 2.5% at AFL, and HDB checks your income for the grant and HDB loan about 3 months before key collection, when you’re more likely to be working.',
  workStart: 'If you’re still studying or in NS, set when you expect to start full-time work. Before that month the app assumes no salary, no CPF and no bonus.',
  household: 'First-timers have never owned or bought a subsidised flat or received a housing grant. It decides which grants you get and which BTO queue you’re in.',
  stepUp: 'Step-Up CPF Housing Grant: $15,000 for second-timer families moving from public rental or a 2-room flat to a 2-room Flexi or 3-room Standard flat, with household income up to $7,000.',
  citizenship: 'Singapore PRs pay lower (graduated) CPF rates in their first two years. A citizen + PR couple pays $10,000 more for a BTO flat; two PRs can’t buy a BTO flat.',
  selfEmployed: 'Self-employed people have no employer CPF. Only voluntary top-ups go into your OA, so plan to pay more in cash.',
  cpfLimit: 'With a bank loan you can use CPF for the flat up to its value (the Valuation Limit). Past that, only if you’ve set aside the Basic Retirement Sum, up to 120%. With an HDB loan there’s no such cap.',
  lockIn: 'Bank packages are often fixed for 2–3 years, then move to a floating rate. Set the rate you expect after that.',
  inflation: 'Prices of your own costs (renovation, furniture, rent, wedding…) rise each year by this much. Official fees aren’t inflated.',
  cashInterest: 'Interest your cash savings earn in the bank, e.g. from a high-yield savings account.',
  voluntaryCpf: 'Extra money you choose to put into CPF from your cash. It’s split across Ordinary, Special and MediSave accounts like normal contributions, so only part reaches your OA for the flat. Normal + voluntary contributions can’t exceed $37,740 a year.',
  inflow: 'Cash you expect to receive, added to your savings in that month. It’s not counted as a payment.',
  incomeChanges: 'Plan for pay that isn’t steady: a new job or pay cut from a month, time without income (job loss, sabbatical, study), or a different raise in a particular year. Losing income also affects your housing grant and loan eligibility if it falls in the months HDB looks at.',
  whatIf: 'We re-run your plan with one of you earning nothing for a few months, while your usual living costs (take-home pay minus what you save) come out of savings.',
  loanChanges: 'What happens to your mortgage later. Bank rates usually float after a 2–3 year fixed period, so add a rate change for each period. You can switch from an HDB loan to a bank loan (but never back), refinance between banks, or shorten/lengthen the tenure. Each change re-works the monthly instalment on what you still owe.',
  LTV: 'Loan-to-Value: the most you can borrow as a share of the price. 75% for both HDB and bank loans now.',
  hdbLoan: 'Loan from HDB at 2.6% (0.1% above the CPF OA rate). You must use your OA savings first, keeping at most $20k each.',
  bankLoan: 'Loan from a bank. Rates can be lower but may change. At least 5% of the price must be paid in cash, and you need the bank’s Letter of Offer before signing the AFL. You can’t switch from a bank loan to an HDB loan later.',
  MSR: 'Mortgage Servicing Ratio: your monthly mortgage as a share of gross monthly income. Must be 30% or less for HDB flats. Lenders test this at a higher "stress" interest rate.',
  TDSR: 'Total Debt Servicing Ratio: all monthly debt repayments (mortgage + car loan etc.) as a share of income. Must be 55% or less for bank loans.',
  stress: 'Lenders check affordability as if interest were higher (3% for HDB loans, 4% for bank loans) so you can cope if rates rise.',
  grant: 'Housing grants (e.g. Enhanced CPF Housing Grant, up to $120k) are paid into your CPF OA and must be used for the flat. They reduce what you pay.',
  EHG: 'Enhanced CPF Housing Grant: up to $120,000 for first-timer families, depending on household income (ceiling $9,000/month). The only main grant for BTO flats.',
  accrued: 'Accrued interest: the 2.5% a year your CPF would have earned if you had not used it for the flat. When you sell, you must put back what you used plus this interest into your own CPF (it’s your money, not a fee).',
  HPS: 'Home Protection Scheme: mortgage insurance that pays off your HDB loan if you die or become disabled. Premiums are paid yearly from CPF OA.',
  fire: 'HDB fire insurance: compulsory if you have an HDB loan. A few dollars for 5 years, paid in cash.',
  legal: 'Conveyancing / legal fees for the lease and mortgage documents. With an HDB loan, HDB’s lawyers charge a small tiered fee. With a bank loan, you hire a private lawyer (~$2,500–$3,000).',
  classification: 'Standard, Plus and Prime flats differ in location and resale rules. Plus/Prime flats have a 10-year minimum occupation period and HDB takes back part of the subsidy when you sell.',
  cpfSlider: 'For payments where CPF is allowed, how much you want to pay from CPF (the rest from cash). Using more CPF keeps cash for renovation but means more accrued interest.',
  interim: 'Where you live while waiting for the flat. Rent comes out of your cash every month until key collection.',
  buffer: 'How much cash and CPF you have left right after collecting keys.',
  leanest: 'The month where your combined cash is lowest.',
  poolCash: 'If one of you runs short of cash, the other chips in. Turn off to check each person separately.',
  jointSplit: 'How joint payments (downpayment, fees, renovation) are shared between you.',
} as const

export type Term = keyof typeof GLOSSARY
